jwt.cookie.name=refresh_token
jwt.cookie.secure=false
jwt.cookie.same-site=Lax

app.frontend-url=http://localhost:5173

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG