CREATE TABLE item_rating
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT                                  NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    item_type  VARCHAR(255)                            NOT NULL,
    meal       VARCHAR(255)                            NOT NULL,
    rating     INTEGER                                 NOT NULL,
    tags       TEXT[],
    suggestion VARCHAR(100),
    rated_date date                                    NOT NULL,
    CONSTRAINT pk_item_rating PRIMARY KEY (id)
);



ALTER TABLE item_rating
    ADD CONSTRAINT uk_student_item_meal_date UNIQUE (student_id, item_id, item_type, meal, rated_date);

ALTER TABLE item_rating
    ADD CONSTRAINT FK_ITEM_RATING_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);
