CREATE SEQUENCE IF NOT EXISTS accountant_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE accountant
(
    id      BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL,
    user_id BIGINT       NOT NULL,
    phone   VARCHAR(255),
    CONSTRAINT pk_accountant PRIMARY KEY (id)
);

CREATE TABLE diet_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    veg         BOOLEAN                                 NOT NULL,
    price       INTEGER,
    CONSTRAINT pk_diet_items PRIMARY KEY (id)
);

CREATE TABLE extra_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_extra_items PRIMARY KEY (id)
);

CREATE TABLE hostel
(
    id            BIGINT       NOT NULL,
    name          VARCHAR(255) NOT NULL,
    residents     VARCHAR(255) NOT NULL,
    accountant_id BIGINT,
    email         VARCHAR(255),
    phone         VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_hostel PRIMARY KEY (id)
);

CREATE TABLE menu_diet
(
    diet_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL
);

CREATE TABLE menu_extra
(
    extra_id BIGINT NOT NULL,
    menu_id  BIGINT NOT NULL
);

CREATE TABLE mess_menu
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    week_day   VARCHAR(255)                            NOT NULL,
    start_time time(6) WITHOUT TIME ZONE               NOT NULL,
    end_time   time(6) WITHOUT TIME ZONE               NOT NULL,
    is_active  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_mess_menu PRIMARY KEY (id)
);

CREATE TABLE otp_challenges
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identifier  VARCHAR(255)                            NOT NULL,
    purpose     VARCHAR(255)                            NOT NULL,
    otp_hash    VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    expires_at  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    attempts    INTEGER                                 NOT NULL,
    verified    BOOLEAN                                 NOT NULL,
    verified_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_otp_challenges PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash       VARCHAR(255)                            NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    expiry_date      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    revoked          BOOLEAN                                 NOT NULL,
    replaced_by_hash VARCHAR(64),
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE student_diet
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT                                  NOT NULL,
    date       date,
    type       VARCHAR(255)                            NOT NULL,
    price      DECIMAL,
    CONSTRAINT pk_student_diet PRIMARY KEY (id)
);

CREATE TABLE student_extra
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT                                  NOT NULL,
    extra_id   BIGINT                                  NOT NULL,
    date       date,
    quantity   INTEGER,
    price      DECIMAL,
    CONSTRAINT pk_student_extra PRIMARY KEY (id)
);

CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    roll_no    VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    hostel_no  BIGINT                                  NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT       NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    verified BOOLEAN      NOT NULL,
    enabled  BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE mess_menu
    ADD CONSTRAINT uc_a3b977a6499b7d890cf008a05 UNIQUE (week_day, type);

ALTER TABLE accountant
    ADD CONSTRAINT uc_accountant_user UNIQUE (user_id);

ALTER TABLE hostel
    ADD CONSTRAINT uc_hostel_accountant UNIQUE (accountant_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token_hash UNIQUE (token_hash);

ALTER TABLE students
    ADD CONSTRAINT uc_students_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_otp_identifier_purpose ON otp_challenges (identifier, purpose);

CREATE INDEX idx_token_hash ON refresh_tokens (token_hash);

ALTER TABLE accountant
    ADD CONSTRAINT FK_ACCOUNTANT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE hostel
    ADD CONSTRAINT FK_HOSTEL_ON_ACCOUNTANT FOREIGN KEY (accountant_id) REFERENCES accountant (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_HOSTEL_NO FOREIGN KEY (hostel_no) REFERENCES hostel (id);

ALTER TABLE students
    ADD CONSTRAINT FK_STUDENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE student_diet
    ADD CONSTRAINT FK_STUDENT_DIET_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE student_extra
    ADD CONSTRAINT FK_STUDENT_EXTRA_ON_EXTRA FOREIGN KEY (extra_id) REFERENCES extra_items (id);

ALTER TABLE student_extra
    ADD CONSTRAINT FK_STUDENT_EXTRA_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE menu_extra
    ADD CONSTRAINT fk_menext_on_extra_item FOREIGN KEY (extra_id) REFERENCES extra_items (id);

ALTER TABLE menu_extra
    ADD CONSTRAINT fk_menext_on_menu FOREIGN KEY (menu_id) REFERENCES mess_menu (id);

ALTER TABLE menu_diet
    ADD CONSTRAINT fk_menu_diet_on_diet_item FOREIGN KEY (diet_id) REFERENCES diet_items (id);

ALTER TABLE menu_diet
    ADD CONSTRAINT fk_menu_diet_on_menu FOREIGN KEY (menu_id) REFERENCES mess_menu (id);
