CREATE TABLE hostel_menu_plan
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hostel_id    BIGINT                                  NOT NULL,
    mess_slot_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hostel_menu_plan PRIMARY KEY (id)
);

ALTER TABLE hostel_menu_plan
    ADD CONSTRAINT uc_8fdfc6e67fb68c4c0ce84e073 UNIQUE (hostel_id, mess_slot_id);

ALTER TABLE hostel_menu_plan
    ADD CONSTRAINT FK_HOSTEL_MENU_PLAN_ON_MESS_SLOT FOREIGN KEY (mess_slot_id) REFERENCES mess_slot (id);

ALTER TABLE menu_diet
    ADD created_at TIMESTAMP(6) WITHOUT TIME ZONE;

ALTER TABLE menu_diet
    ADD updated_at TIMESTAMP(6) WITHOUT TIME ZONE;

ALTER TABLE menu_diet
    ADD menu_plan_id BIGINT;

ALTER TABLE menu_diet
    DROP CONSTRAINT pk_menu_diet;

ALTER TABLE menu_diet
    ADD CONSTRAINT pk_menu_diet PRIMARY KEY (menu_plan_id, diet_id);

ALTER TABLE menu_diet
    DROP CONSTRAINT fk_menu_diet_on_menu;

ALTER TABLE menu_diet
    ADD CONSTRAINT FK_MENU_DIET_ON_MENU_PLAN FOREIGN KEY (menu_plan_id) REFERENCES hostel_menu_plan (id);

ALTER TABLE menu_diet
    DROP COLUMN mess_slot_id;

ALTER TABLE menu_diet
    DROP CONSTRAINT fk_menu_diet_on_mess_slot;

ALTER TABLE menu_diet
    ADD CONSTRAINT FK_MENU_DIET_ON_DIET_ITEM FOREIGN KEY (diet_id) REFERENCES diet_items (id);


ALTER TABLE menu_extra
    ADD menu_plan_id BIGINT;

ALTER TABLE menu_extra
    DROP CONSTRAINT pk_menu_extra;

ALTER TABLE menu_extra
    ADD CONSTRAINT pk_menu_extra PRIMARY KEY (menu_plan_id, extra_id);


ALTER TABLE menu_extra
    DROP CONSTRAINT fk_menext_on_menu;

ALTER TABLE menu_extra
    ADD CONSTRAINT FK_MENU_EXTRA_ON_MENU_PLAN FOREIGN KEY (menu_plan_id) REFERENCES hostel_menu_plan (id);

ALTER TABLE menu_extra
    DROP COLUMN mess_slot_id;

ALTER TABLE menu_extra
    DROP CONSTRAINT fk_menu_extra_on_mess_slot;

ALTER TABLE menu_extra
    ADD CONSTRAINT FK_MENU_EXTRA_ON_EXTRA_ITEM FOREIGN KEY (extra_id) REFERENCES extra_items (id);


ALTER TABLE mess_slot
    DROP COLUMN created_at;

ALTER TABLE mess_slot
    DROP COLUMN updated_at;